name: cfljam_MAPNET_POPGEN
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.2=h0371630_0
  - pip=10.0.1=py37_0
  - r-essentials
  - mro-base
  - singularity
  - samtools 
  - angsd
  - pip:
    - osfclient==0.0.3
